### ISSUE TITLE
Fix entity calls

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/uuid#3]
This relies on some entity functions, some of which exist now in entity_plus and some which require a change in this module.

**Comment by herbdool** [comment]
I've provided a PR which mostly fixes the `entity_save()` and `entity_delete` calls and fixes the way node settings are accessed. I also did some simple fixes of replacing drupal_ with backdrop_, removed old update hooks.

@klonos @cellear @stpaultim 

The module does generate UUIDs so it's mostly working.

**Comment by argiepiano** [comment]
I have reviewed this PR - it looks good to me. I haven't tested the module, though. @cellear, is this something you can do? It'd be good to have a working version of this very popular D7 module.

**Comment by argiepiano** [comment]
@cellear, @klonos, as maintainers, are you OK merging this PR? I could do that as @backdrop-contrib/bug-squad if you wish. Let us know.

**Comment by herbdool** [comment]
Merged on behalf of the @backdrop-contrib/bug-squad.

**Comment by herbdool** [comment]
@argiepiano I figure it's had enough time to review.

**Comment by argiepiano** [comment]
Should we do a release?

**Comment by herbdool** [comment]
@argiepiano if it was a bug fix release, sure. But this module currently has no release at all.

Better to get a volunteer to help maintain. Perhaps @klonos and @cellear have lost interest.
